# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8f6a4875fde5ab38f211129a99c62263f431ef3a8f9abff0d108fb2ce679c686bfba760904c55c2a0655a5d899fd7da4249137315ad985dabc4a2f708e112491

test:
  secret_key_base: 2ed5be43289f965c6dc83ec9f520fef768cd52990499076b302b4d5aa7724cea8727b6dc53c5ab92e70f1523485f26cfa29ae4281adf1bd7e4cdaf244e9942cd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
